#!/bin/sh
#
# @name Gazebo x500 depth
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_depth_down}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# GPS-denied external vision defaults
param set-default SYS_HAS_GPS 0
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_HGT_REF 3
param set-default EKF2_BARO_CTRL 1
param set-default EKF2_EV_CTRL 7
param set-default EKF2_EV_DELAY 50.0
param set-default EKF2_EV_NOISE_MD 0
param set-default EKF2_EVP_NOISE 0.05
param set-default EKF2_EVV_NOISE 0.10
param set-default EKF2_EVA_NOISE 0.10
param set-default EKF2_EVP_GATE 5.0
param set-default EKF2_EVV_GATE 3.0
param set-default EKF2_EV_QMIN 0
param set-default EKF2_EV_POS_X 0.12
param set-default EKF2_EV_POS_Y -0.03
param set-default EKF2_EV_POS_Z -0.242
param set-default COM_RCL_EXCEPT 4
param set-default NAV_DLL_ACT 0
param set-default NAV_RCL_ACT 0
param set-default COM_ARM_WO_GPS 1
param set-default COM_RC_IN_MODE 4
param set-default COM_OBL_RC_ACT 1
param set-default COM_POSCTL_NAVL 0

